export const wardsList = [
  // Adamaawa State
  {
    state: "ADAMAWA",
    lga: "DEMSA",
    wards: [
      "BILLE",
      "BORRONG",
      "DEMSA",
      "DILLI",
      "DONG",
      "DWAM",
      "GWAMBA",
      "KPASHAM",
      "MBULA KULI",
      "NASSARAWO DEMSA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "FUFORE",
    wards: [
      "BETI",
      "FARANG",
      "FUFORE",
      "GURIN",
      "KARLAHI",
      "MAYO INE",
      "PARIYA",
      "RIBADU",
      "UKI TUKI",
      "WURO BOKKI",
      "YADIM",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GANYE",
    wards: [
      "BAKARI GUSO",
      "GAMU",
      "GANYE I",
      "GANYE II",
      "GURUM",
      "JAGGU",
      "SANGASUMI",
      "SUGU",
      "TIMDORE",
      "YEBBI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GIREI",
    wards: [
      "DAKRI",
      "DAMARE",
      "GERENG",
      "GIREI I",
      "GIREI II",
      "JERA BAKARI",
      "JERA BONYO",
      "MODIRE/ VINIKILANG",
      "TAMBO",
      "WURO DOLE",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GOMBI",
    wards: [
      "BOGA/ DINGAI",
      "DUWA",
      "GA'ANDA",
      "GABUN",
      "GARKIDA",
      "GOMBI NORTH",
      "GOMBI SOUTH",
      "GUYAKU",
      "TAWA",
      "YANG",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GUYUK",
    wards: [
      "BANJIRAM",
      "BOBINI",
      "BODENO",
      "CHIKILA",
      "DUKUL",
      "DUMNA",
      "GUYUK",
      "KOLA",
      "LOKORO",
      "PUROKAYO",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "HONG",
    wards: [
      "BANGSHIKA",
      "DAKSIRI",
      "GARAHA",
      "GAYA",
      "HILDI",
      "HONG",
      "HUSHERE ZUM",
      "KWARHI",
      "MAYO LOPE",
      "SHANGUI",
      "THILBANG",
      "UBA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "JADA",
    wards: [
      "DANABA",
      "JADA I",
      "JADA II",
      "KOMA I",
      "KOMA II",
      "LEKO",
      "MAPEO",
      "MAYOKALAYE",
      "MBULO",
      "NYIBANGO",
      "YELLI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "LAMURDE",
    wards: [
      "DUBWANGUN",
      "GYAWANA",
      "LAFIYA",
      "LAMURDE",
      "MGBEBONGUN",
      "NGBAKOWO",
      "OPALO",
      "RIGANGE",
      "SUWA",
      "WADUKU",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MADAGALI",
    wards: [
      "BABEL",
      "DUHU/ SHUWA",
      "GULAK",
      "HYAMBULA",
      "K/WURO NGAYANDI",
      "MADAGALI",
      "PALLAM",
      "SHELMI / SUKUR/ VAPURA",
      "WAGGA",
      "WULA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MAYO - BELWA",
    wards: [
      "BAJAMA",
      "BINYERI",
      "GANGFADA",
      "GENGLE",
      "GOROBI",
      "MAYO FARANG",
      "MAYO-BELWA",
      "NASSARAWO JERENG",
      "NDIKONG",
      "RIBADU",
      "TOLA",
      "YOFFO",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MICHIKA",
    wards: [
      "BAZZA MARGI",
      "FUTUDOU / FUTULES",
      "GARTA / GHUNCHI",
      "JIGALAMBU",
      "MADZI",
      "MICHIKA I",
      "MICHIKA II",
      "MINKISI/ WURO NGIKI",
      "MODA / DLAKA / GHENJUWA",
      "MUNKAVICITA",
      "SINA / KAMALE / KWANDE",
      "SUKUMU / TILLIJO",
      "THUKUDOU / SUFUKU / ZAH",
      "TUMBARA / NGABILI",
      "VI / BOKA",
      "WAMBLIMI / TILLI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MUBI NORTH",
    wards: [
      "BAHULI",
      "BETSO",
      "DIGIL",
      "KOLERE",
      "LOKUWA",
      "MAYO BANI",
      "MIJILU",
      "MUCHALLA",
      "SABON LAYI",
      "VIMTIM",
      "YELWA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MUBI SOUTH",
    wards: [
      "DIRBISHI/GANDIRA",
      "DUVU/ CHABA/ GIRBURUM",
      "GELLA",
      "GUDE",
      "KWAJA",
      "LAMORDE",
      "MUGULBU/ YADAFA",
      "MUJARA",
      "NASSARAWO",
      "NDUKU",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "NUMAN",
    wards: [
      "BARE",
      "BOLKI",
      "GAMADIO",
      "IMBURU",
      "KODOMTI",
      "NUMAN I",
      "NUMAN II",
      "NUMAN III",
      "SABON PEGI",
      "VULPI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "SHELLENG",
    wards: [
      "BAKTA",
      "BODWAI",
      "GUNDO",
      "GWAPOPOLOK",
      "JUMBUL",
      "KETEMBERE",
      "KIRI",
      "LIBBO",
      "SHELLENG",
      "TALLUM",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "SONG",
    wards: [
      "DIRMA",
      "DUMNE",
      "GUDU MBOI",
      "KILANGE FUNA",
      "KILANGE HIRNA",
      "SIGIRE",
      "SONG GARI",
      "SONG WAJE",
      "SUKTU",
      "WALTANDI",
      "ZUMO",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "TOUNGO",
    wards: [
      "DAWO I",
      "DAWO II",
      "GUMTI",
      "KIRI I",
      "KIRI II",
      "KONGIN BABA I",
      "KONGIN BABA II",
      "TOUNGO I",
      "TOUNGO II",
      "TOUNGO III",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "YOLA NORTH",
    wards: [
      "AJIYA",
      "ALKALAWA",
      "DOUBELI",
      "GWADABAWA",
      "JAMBUTU",
      "KARENA",
      "LIMAWA",
      "LUGGERE",
      "NASSARAWO",
      "RUMDE",
      "YELWA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "YOLA SOUTH",
    wards: [
      "ADARAWO",
      "BAKO",
      "BOLE YOLDE PATE",
      "MAKAMA 'A'",
      "MAKAMA 'B'",
      "MBAMBA",
      "MBAMOI",
      "NAMTARI",
      "NGURORE",
      "TOUNGO",
      "YOLDE KOHI",
    ],
  },
  // Taraba State
  {
    state: "TARABA",
    lga: "ARDO - KOLA",
    wards: [
      "ALIM GORA",
      "ARDO KOLA",
      "IWARE",
      "JAURO YINU",
      "LAMIDO BORNO",
      "MAYO RANEWO",
      "SARKIN DUTSE",
      "SUNKANI",
      "TAU",
      "ZONGON KOMBI",
    ],
  },
  {
    state: "TARABA",
    lga: "BALI",
    wards: [
      "BADAKOSHI",
      "BALI A",
      "BALI B",
      "GANG DOLE",
      "GANG MATA",
      "GANGLARI",
      "GANGTIBA",
      "KAIGAMA",
      "MAIHULA",
      "SUNTAI",
      "TAKALAFIYA",
    ],
  },
  {
    state: "TARABA",
    lga: "DONGA",
    wards: [
      "AKATE",
      "ASIBITI",
      "BIKADARKO",
      "FADA",
      "GAYAMA",
      "GINDIN DUTSE",
      "GYATTA AURE",
      "MARARRABA",
      "NYITA",
      "SUNTAI",
    ],
  },
  {
    state: "TARABA",
    lga: "GASHAKA",
    wards: [
      "GALUMJINA",
      "GANGUMI",
      "GARBABI",
      "GASHAKA",
      "GAYAM",
      "JAMTARI",
      "MAI-IDANU",
      "MAYO SELBE",
      "SERTI 'A'",
      "SERTI 'B'",
    ],
  },
  {
    state: "TARABA",
    lga: "GASSOL",
    wards: [
      "GASSOL",
      "GUNDUMA",
      "MUTUM BIYU I",
      "MUTUM BIYU II",
      "NAM NAI",
      "SABON GIDA",
      "SARKIN SHIRA",
      "SENDIRDE",
      "TUTARE",
      "WUROJAM",
      "WURYO",
      "YARIMA",
    ],
  },
  {
    state: "TARABA",
    lga: "IBI",
    wards: [
      "DAMPAR I",
      "DAMPAR II",
      "DAMPAR III",
      "IBI NWONYO I",
      "IBI NWONYO II",
      "IBI RIMI UKU I",
      "IBI RIMI UKU II",
      "SARKIN KUDU I",
      "SARKIN KUDU II",
      "SARKIN KUDU III",
    ],
  },
  {
    state: "TARABA",
    lga: "JALINGO",
    wards: [
      "ABBARE YELWA",
      "BARADE",
      "KACHALLA SEMBE",
      "KONA",
      "MAJIDADI",
      "MAYO GOI",
      "SARKIN DAWAKI",
      "SINTALI",
      "TURAKI A",
      "TURAKI B",
    ],
  },
  {
    state: "TARABA",
    lga: "KARIM-LAMIDO",
    wards: [
      "AMAR",
      "ANDAMIN",
      "BACHAMA",
      "BIKWIN",
      "DAROFAI",
      "DIDANGO",
      "JEN ARDIDO",
      "JEN KAIGAMA",
      "KARIM A",
      "KARIM B",
      "KWANCHI",
    ],
  },
  {
    state: "TARABA",
    lga: "KURMI",
    wards: [
      "ABONG",
      "AKWENTO/BOKO",
      "ASHUKU/ENEME",
      "BAISSA",
      "BENTE/GALEA",
      "BISSAULA",
      "DIDAN",
      "NDAFORO/GEANDA",
      "NJUWANDE",
      "NYIDO/TOSSO",
    ],
  },
  {
    state: "TARABA",
    lga: "LAU",
    wards: [
      "ABBARE I",
      "ABBERE II",
      "DONADDA",
      "GARIN DOGO",
      "GARIN MAGAJI",
      "JIMLARI",
      "KUNINI",
      "LAU I",
      "LAU II",
      "MAYO LOPE",
    ],
  },
  {
    state: "TARABA",
    lga: "SARDAUNA",
    wards: [
      "GEMBU A",
      "GEMBU B",
      "KABRI",
      "KAKARA",
      "MAGU",
      "MAYO-NDAGA",
      "MBAMNGA",
      "NDUM-YAJI",
      "NGUROJE",
      "TITONG",
      "WARWAR",
    ],
  },
  {
    state: "TARABA",
    lga: "TAKUM",
    wards: [
      "BETE",
      "BIKASHIBILA",
      "CHANCHANJI",
      "DUTSE",
      "FETE",
      "GAHWETON",
      "MANYA",
      "ROGO",
      "SHIBONG",
      "TIKARI",
      "YUKUBEN",
    ],
  },
  {
    state: "TARABA",
    lga: "USSA",
    wards: [
      "FIKYU",
      "KPAMBO",
      "KPAMBO PURI",
      "KWESATI",
      "LISSAM I",
      "LISSAM II",
      "LUMBU",
      "RUFU",
    ],
  },
  {
    state: "TARABA",
    lga: "WUKARI",
    wards: [
      "AKWANA",
      "AVYI",
      "BANTAJE",
      "CHONKU",
      "HOSPITAL",
      "JIBU",
      "KENTE",
      "PUJE",
      "RAFIN KADA",
      "TSOKUNDI",
    ],
  },
  {
    state: "TARABA",
    lga: "YORRO",
    wards: [
      "BIKASSA I",
      "BIKASSA II",
      "NYAJA I",
      "NYAJA II",
      "PANTISAWA I",
      "PANTISAWA II",
      "PUPULE I",
      "PUPULE II",
      "PUPULE III",
      "SUMBU I",
      "SUMBU II",
    ],
  },
  {
    state: "TARABA",
    lga: "ZING",
    wards: [
      "BITAKO",
      "BUBONG",
      "DINDING",
      "LAMMA",
      "MONKIN A",
      "MONKIN B",
      "YAKOKO",
      "ZING AI",
      "ZING AII",
      "ZING B",
    ],
  },
  {
    state: "BAUCHI",
    lga: "ALKALERI",
    wards: [
      "ALKALERI",
      "BIRIN/ GIGARA/ YANKARI",
      "DAN KUNGIBAR",
      "FUTUK",
      "GAR",
      "GWANA / MANSUR",
      "GWARAM",
      "MAIMADI",
      "PALI",
      "YALO",
      "YULI/ LIM",
    ],
  },
  {
    state: "BAUCHI",
    lga: "BAUCHI",
    wards: [
      "BIRSHI/MIRI",
      "DANDANGO/YAMRAT",
      "DAN'IYA HARDO",
      "DAWAKI",
      "GALAMBI/GWASKWARAM",
      "KANGYARE/TURWUN",
      "KUNDUM/DURUM",
      "MAJIDADI 'A'",
      "MAJIDADI 'B'",
      "MAKAMA/SARKI BAKI",
      "MUN/MUNSAL",
      "ZUNGUR/LIMAN KATAGUM",
    ],
  },
  {
    state: "BAUCHI",
    lga: "BOGORO",
    wards: [
      "B O I A",
      "B O I B",
      "B O I C",
      "BOGORO A",
      "BOGORO B",
      "BOGORO C",
      "BOGORO D",
      "LUSA A",
      "LUSA B",
      "LUSA C",
    ],
  },
  {
    state: "BAUCHI",
    lga: "DAMBAM",
    wards: [
      "DAGAUDA",
      "DAMBAM",
      "GARGAWA",
      "GARUZA",
      "GURBANA",
      "JALAM CENTRAL",
      "JALAM EAST",
      "YAME",
      "YANDA",
      "ZAURA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "DARAZO",
    wards: [
      "DARAZO",
      "GABARIN",
      "GABCIYARI",
      "KONKIYAL",
      "LAGO",
      "LANZAI",
      "PAPA",
      "SADE",
      "TAUYA",
      "WAHU",
      "YAUTARE",
    ],
  },
  {
    state: "BAUCHI",
    lga: "DASS",
    wards: [
      "BAGEL/BAJAR",
      "BARAZA",
      "BUNDOT",
      "BUNUNU CENTRAL",
      "BUNUNU SOUTH",
      "DOTT",
      "DURR",
      "POLCHI",
      "WANDI",
      "ZUMBUL/LUKSHI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "GAMAWA",
    wards: [
      "ALAGARNO/JADORI",
      "GADIYA",
      "GAMAWA",
      "GOLOLO",
      "KAFIN ROMI",
      "KUBDIYA",
      "RAGA",
      "TARMASUWA",
      "TUMBI",
      "UDUBO",
      "ZINDI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "GANJUWA",
    wards: [
      "Ganjuwa",
      "Gungura",
      "KAFIN MADAKI",
      "KARIYA",
      "Kubi East",
      "Kubi West",
      "MIYA EAST",
      "MIYA WEST",
      "NASARAWA SOUTH",
      "NASARAWA NORTH",
      "YALI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "GIADE",
    wards: [],
  },
  {
    state: "BAUCHI",
    lga: "ITAS/GADAU",
    wards: [
      "CHINKANI",
      "DOGUWA SOUTH",
      "DOGUWA CENTRAL",
      "GIADE",
      "ISAWA",
      "SABON SARA",
      "UZUM A",
      "UZUM B",
      "ZABI",
      "ZIRRAMI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "JAMA'ARE",
    wards: [
      "DOGON JEJI A",
      "DOGON JEJI B",
      "DOGON JEJI C",
      "GALDIMARI",
      "HANAFARI",
      "JAMA'ARE A",
      "JAMA'ARE B",
      "JAMA'ARE C",
      "JAMA'ARE D",
      "JURARA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "KATAGUM",
    wards: [
      "BULKACHUWA/DAGARO",
      "BUSKURI",
      "CHINADE",
      "GAMBAKI/BIDIR",
      "MADACHI/GANGAI",
      "MADANGALA",
      "MADARA",
      "NASARAWA BAKIN KASUWA",
      "RAGWAM/MAGONSHI",
      "TSAKUWA KOFAR GABAS/ KOFAR KUKA",
      "YAYU",
    ],
  },
  {
    state: "BAUCHI",
    lga: "KIRFI",
    wards: [
      "BADARA",
      "BARA",
      "BENI A",
      "BENI B",
      "DEWU CENTRAL",
      "DEWU EAST",
      "KIRFI",
      "SHANGO",
      "TUBULE",
      "WANKA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "MISAU",
    wards: [
      "AJILIN/GUGULIN",
      "BETI",
      "GWARAM",
      "HARDAWA",
      "JARKASA",
      "KUKADI/GUNDARI",
      "SARMA/AKUYAM",
      "SIRKO",
      "TOFU",
      "ZADAWA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "NINGI",
    wards: [
      "BALMA",
      "BASHE",
      "BURRA / KYATA",
      "DINGIS",
      "JANGU",
      "KUDU / YAMMA",
      "KURMI",
      "NASARU",
      "NINGI",
      "SAMA",
      "TIFFI / GUDA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "SHIRA",
    wards: [
      "ANDUBUN",
      "BELI/GAGIDABA",
      "BUKUL/BANGIRE",
      "DISINA",
      "FAGGO",
      "KILBORI",
      "SAMBUWAL",
      "SHIRA",
      "TSAFI",
      "TUMFAFI",
      "ZUBO",
    ],
  },
  {
    state: "BAUCHI",
    lga: "TAFAWA BALEWA",
    wards: [
      "BALL",
      "BULA",
      "BUNUNU",
      "DAJIN",
      "DULL",
      "KARDAM A",
      "KARDAM B",
      "LERE SOUTH",
      "LERE NORTH",
      "TAPSHIN",
      "WAI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "TORO",
    wards: [
      "JAMA'A / ZARANDA",
      "LAME",
      "MARA / PALAMA",
      "RAHAMA",
      "RAUTA / GEJI",
      "RIBINA",
      "TAMA",
      "TILDEN FULANI",
      "TORO / TULAI",
      "WONU",
      "ZALAU / RISHI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "WARJI",
    wards: [
      "BAIMA SOUTH/EAST",
      "BAIMA NORTH / WEST",
      "DAGU EAST",
      "DAGU WEST",
      "GABANGA",
      "KATANGA",
      "KILBORI",
      "RANGAN",
      "TIYIN",
      "TUDUN WADA WEST",
    ],
  },
  {
    state: "BAUCHI",
    lga: "ZAKI",
    wards: [
      "ALANGAWARI / KAFIN / LARABAWA",
      "BURSALI",
      "GUMAI",
      "KATAGUM",
      "MAINAKO",
      "MAIWA",
      "MAKAWA",
      "MURMUR SOUTH",
      "MURMUR NORTH",
      "SAKWA",
      "TASHENA / GADAI",
    ],
  },
  // ABUJA
  {
    state: "ABUJA-FCT",
    lga: "ABAJI",
    wards: [
      "Abaji Central",
      "Abaji North East",
      "Abaji South East",
      "Agyana/pandagi",
      "Alu Mamagi",
      "Gawu",
      "Gurdi",
      "Nuku",
      "Rimba Ebagi",
      "Yaba",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "ABUJA MUNICIPAL",
    wards: [
      "City Centre",
      "Garki",
      "Gui",
      "Gwagwa",
      "Gwarinpa",
      "Jiwa",
      "Kabusa",
      "Karshi",
      "Karu",
      "Nyanya",
      "Orozo",
      "Wuse",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "BWARI",
    wards: [
      "Bwari Central",
      "Byazhin",
      "Dutse Alhaji",
      "Igu",
      "Kawu",
      "Kubwa",
      "Kuduru",
      "Shere",
      "Ushafa",
      "Usuma",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "GWAGWALADA",
    wards: [
      "Dobi",
      "Gwagwalada Centre",
      "Gwako",
      "Ibwa",
      "Ikwa",
      "Kutunku",
      "Paiko",
      "Staff Quarters",
      "Tungan Maje",
      "Zuba",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "KWALI",
    wards: [
      "ASHARA",
      "DAFA",
      "GUMBO",
      "KILANKWA",
      "KUNDU",
      "KWALI CENTRAL",
      "PAI",
      "YANGOJI",
      "YEBU",
      "WAKO",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "KUJE",
    wards: [
      "CHIBIRI",
      "GAUBE",
      "GUDUNKARIYA",
      "GWARGWADA",
      "KABI",
      "KUJE CENTRAL",
      "KUJEKWA",
      "KWAKU",
      "RUBOCHI",
      "YENCHE",
    ],
  },
];
